export {
  LEARNING_ITEM_TYPES,
  LEARNING_ITEM_TYPE_LABEL,
  LEARNING_STATUSES,
  LEARNING_STATUS_LABEL,
  MAX_LESSONS,
  learningItemTypeSchema,
  learningStatusSchema,
  learningItemSchema,
  learningItemCreateSchema,
  learningItemUpdateSchema,
  learningItemFormSchema,
  learningItemInputFromForm,
  emptyLesson,
  lessonProgress,
  studySessionSchema,
  studySessionCreateSchema,
  studySessionUpdateSchema,
  studySessionFormSchema,
  studySessionInputFromForm,
  type LearningItem,
  type LearningItemCreate,
  type LearningItemUpdate,
  type LearningItemFormValues,
  type LearningItemType,
  type LearningStatus,
  type Lesson,
  type StudySession,
  type StudySessionCreate,
  type StudySessionUpdate,
  type StudySessionFormValues,
} from "./schema";
export { summarizeLearning, studyMinutesForItem, type LearningStats } from "./learning-stats";
export {
  analyzePlanLearning,
  buildLearningInsights,
  calculateLearningConfidence,
  compareExpectedVsActual,
  correctLearningPattern,
  createLearningEvent,
  detectLearningPatterns,
  dismissPattern,
  isLearningAuthorizationValid,
  recordDecisionOutcome,
  recordPredictionOutcome,
  recordRecommendationFeedback,
  resetLearning,
  type DecisionOutcome,
  type LearningConfidence,
  type LearningEvent,
  type LearningEventType,
  type LearningInsight,
  type LearningPattern,
  type LearningPatternCategory,
  type LearningPatternStatus,
  type LearningSourceType,
  type PlanLearningResult,
  type PlanLearningSample,
  type PredictionOutcome,
  type RecommendationFeedback,
  type RecommendationFeedbackStatus,
} from "./learning-engine";
export { learningItemRepository, listActiveLearningItems } from "./learning-item-repository";
export { studySessionRepository, listRecentStudySessions } from "./study-session-repository";
export { useLearning } from "./use-learning";
export { LearningView } from "./components/LearningView";
